### ISSUE TITLE
ImageMagick - new version

### ISSUE THREAD

**Issue by floriandd2ba** [winbench/apps-default#6]
Hi,

the version changed. 7.0.8-5 is not more available.
* ID: `Bench.ImageMagick`
* Version: 7.0.8-6

THX

**Comment by mastersign** [comment]
ImageMagick is one of the bad cases, where they publish updates quite often, but do not keep the old releases in a download archive. In this case I copy the release to a private web space, to provide a more stable URL. Not my preferred way, but for now I have no better idea.

There are already a number of binaries I host on my web space &ndash; for the same reason, or because the original download source is not permanently available.
